import Layout from "@/components/layouts/Layout";
import "./globals.css";

export const metadata = {
  title: "iwco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
